### ISSUE TITLE
Tx/Common: xDai Support

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1323]
Part of #1288 

The [xDai chain](https://www.xdaichain.com/) is an EVM sidechain having a native stable token. It is a bit hard to find some necessary developer information. There is a section [developer ressources](https://www.xdaichain.com/for-developers/developer-resources) in the docs, information on testnets is completely hidden (or I overlooked), at some point I stumbled upon the following GitHub repo stating that there are some testnets: https://github.com/poanetwork/poa-chain-spec/tree/dai

I also didn't find any information on a tx format. There is a [block explorer](https://blockscout.com/xdai/mainnet/) though. From looking at an exemplaric [tx](https://blockscout.com/xdai/mainnet/tx/0xfab5c387b239df197fcd163e57b5f35456f91972f58fb53a2e5ba1d85692af4c/internal-transactions) I would cautiously assume that tx format is respectively might be the same as the main chain tx format and the gas provided is then paid in dai instead of ETH and somehow mapped internally or something (attention: wild assumption for now! 😋).

So I guess we should give this a test to connect to some test network, somehow move some (wrapped) DAI over there and try to send a tx (not yet digged further here on the procedure). I might find some additional time to test but generally open for everyone to give this a try.

**Comment by acolytec3** [comment]
https://forum.poa.network/t/getting-started-with-poa-products/2595 This is the PoA network standard set of guidelines. There isn't an xdai testnet per se but I believe the Sokol testnet that's described in those docs mirrors xdai in functionality. Looks like it might be linked to kovan so we could test things out that way

**Comment by holgerd77** [comment]
Yeah, so I was able to send the following successfull [xDai transfer tx](https://blockscout.com/xdai/mainnet/tx/0xfa1c983bea59d273c8508ba21435fd09def92eb2b6ff4ab8fe4f22432cae5171) with the following code:

```typescript
/**
 * Usage:
 * ts-node create-arbitrum-tx.ts PRIVATE_KEY
 */
import { Transaction } from '../ethereumjs-monorepo/packages/tx/src'
import Common from '../ethereumjs-monorepo/packages/common/dist'

const from = '0xaaec86394441f915bce3e6ab399977e9906f3b69'

const PRIV_KEY = process.argv[2]
const to = '0xe13ece23b514caa5b53395c01d0d53d1843258ad'

const common = Common.custom({ chainId: 100 })

const txData = {
  from,
  nonce: 0,
  gasPrice: 1000000000,
  gasLimit: 21000,
  to,
  value: 1,
}

const tx = Transaction.fromTxData(txData, { common })
const signedTx = tx.sign(Buffer.from(PRIV_KEY, 'hex'))

console.log(`0x${signedTx.serialize().toString('hex')}`)
```

**Comment by ryanio** [comment]
Resolved in https://github.com/ethereumjs/ethereumjs-monorepo/pull/1317/commits/082c5f3660b57676e8f5857487708264c035740e

**Comment by sonygod** [comment]
my test 
https://github.com/ethereumjs/ethereumjs-monorepo/issues/1386
is still not work ?why?
